services:
  - type: web
    name: sainik-public-school
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
